### PR TITLE
bump version to 11.7.0

### PR DESCRIPTION
**Pull request by m3vaz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by m3vaz** [comment]
@conda-forge-admin, please rerender

**Review by leofang — APPROVED** [review]

**Comment by leofang** [comment]
@conda-forge/cuda-python Remind me do we need to wait for `cudatoolkit` 11.7 to be released first?

**Comment by m3vaz** [comment]
@leofang We aren't hard tied to the 11.7 cuda toolkit package, since the bindings should work against any 11.X package. So we can release before or after them.

**Comment by jakirkham** [comment]
Thanks Mark and Leo! 🙏

FWIW there is an `automerge` label that can be added to a PR and it will merge the PR automatically after CI passes. If CI fails, it will comment what failed and why it didn't merge. Similarly if something else unexpected happens, it will report the error with details. If other changes get pushed, the label is automatically removed and would need to be readded. Something to consider for future update PRs 🙂

**Pull request merged**
