### PR TITLE
Rebuild v12.6.2 to include missing files

### PR DESCRIPTION
**Pull request by leofang**
xref: https://github.com/NVIDIA/cuda-python/pull/230

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@jakirkham Can the `cdt_name` change from `cos7` to `conda` be considered innocent? Where can I find more information about it? It does not show up in my conda subscription radar...

**Comment by jakirkham** [comment]
> Can the `cdt_name` change from `cos7` to `conda` be considered innocent? Where can I find more information about it? It does not show up in my conda subscription radar...

Yes please see these refs:

* https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6637
* https://github.com/conda-forge/cdt-builds/pull/71
* https://conda-forge.org/community/minutes/2024-05-15/#your-new-agenda-items (need to scroll down a little bit or search `cdt_name`)

**Comment by jakirkham** [comment]
Would it make sense to add a test for this?

Perhaps something simple like...?

```cython
from cuda.ccudart cimport cudaStream_t

def func():
    cdef cudaStream_t s = <cudaStream_t>NULL
```

**Comment by leofang** [comment]
> Yes please see these refs:

Thanks, John. I don't see any place explaining the meaning of `cdt_name=conda` and alternatives than `conda`. Based on Isuru's https://github.com/conda-forge/conda-forge.github.io/issues/1941#issuecomment-1519168703 I assume we are supposed to just ignore `cdt_name` from now on.

**Comment by jakirkham** [comment]
Yes that is what the agenda note reference states (admittedly it is hard to link to the exact line)

**Comment by jakirkham** [comment]
Tbh `cdt_name` is only used when a recipe depends on CDTs, which this one doesn't. So we didn't need to worry about it before either

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
> Would it make sense to add a test for this?

Added a cythonize test. However, if it does not work in one shot I'll revert back to commit eecf59a and proceed to merge, as the needed files are already included as can be seen in the CI log, e.g.
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1077211&view=logs&j=1437f12d-1840-555e-1d60-298e0be353dc&t=e61a9fcc-abec-518f-6f56-33b467894cb6&l=30621
also it's been tested internally. There is no reason to block merging this (and the other) PR. We can move the nice-to-have test to a separate PR.

**Comment by leofang** [comment]
> However, if it does not work in one shot ...

Looks like I need two shots 😛 But it should work now... Set automerge.

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
Thanks for your effort on this @leofang! All looks good to me.

**Comment by leofang** [comment]
I forgot that aarch64 is cross compiled, I wonder what happens with the tests... Are they run in QEMU (I hope so)?

**Comment by leofang** [comment]
Looks like it is. Neat.

**Comment by jakirkham** [comment]
Thanks Leo! 🙏

**Pull request merged**
