### PR TITLE
Added LICENSE file

### PR DESCRIPTION
**Pull request by mmccarty**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Hi Mike, thanks for the PR

Can you please share some more context about this? The source code already contains the license file, which we include in the packages [here]( https://github.com/conda-forge/cuda-python-feedstock/blob/74042fd0acaef98ad6acc667c50046325e837323/recipe/meta.yaml#L50 )

**Comment by mmccarty** [comment]
Thanks @jakirkham Sorry, I meant to add context but got distracted. Someone pointed out to me that the license linked from https://anaconda.org/conda-forge/cuda-python results in a 404. I believe the `license_file` in `recipe/meta.yml` is relative to the `recipe` directory. Adding the file there should fix it?

**Comment by leofang** [comment]
@mmccarty If you're referring to the hyperlink `LicenseRef-NVIDIA-SOFTWARE-LICENSE`, you should just add one more entry `license_url` to `meta.yaml` pointing to CUDA Python's license page. This will not work.

**Comment by jakirkham** [comment]
Thanks for the context Mike. No worries 🙂

Agree with Leo. Would also suggest re-rendering after making that change.

**Comment by leofang** [comment]
ex: https://github.com/conda-forge/cusparselt-feedstock/blob/a38651f7ee8ce4182376664bc7215df842d1326a/recipe/meta.yaml#L71

**Comment by leofang** [comment]
@jakirkham That said, I do notice a few other feedstocks have incorrect hyperlinks too, even though `license_url` has been added:
- https://anaconda.org/conda-forge/cusparselt
- https://anaconda.org/conda-forge/cuquantum

However, the license link of cuTENSOR (https://anaconda.org/conda-forge/cutensor) works. I suspect it has to to with the "LicenseRef-" prefix that we added to suppress the linter complaint (when cuTENSOR was added to conda-forge, it started without the prefix; it's added later after the initial package already lived on anaconda.org). I think there is a bug somewhere in anaconda.org's hyperlink handling (as I checked and didn't spot anything odd in conda-build or conda-smithy).

**Comment by jakirkham** [comment]
Could you please raise new issues on those feedstocks regarding these links?

**Comment by mmccarty** [comment]
@conda-forge-admin, please rerender

**Comment by mmccarty** [comment]
@leofang @jakirkham Looks like that did the trick. At least for the ReadMe. Thanks!

**Review by jakirkham — APPROVED** [review]

**Comment by leofang** [comment]
> Could you please raise new issues on those feedstocks regarding these links?

Thanks @jakirkham for a few good catches, I narrow it down to this list:
- https://github.com/conda-forge/cusparselt-feedstock/issues/14
- https://github.com/conda-forge/cuquantum-python-feedstock/issues/4
- https://github.com/conda-forge/cuquantum-feedstock/issues/3

**Comment by jakirkham** [comment]
Thanks Leo! 😄 Will follow up in those issues

**Review by leofang — APPROVED** [review]

**Comment by leofang** [comment]
Let's see if this change would get the hyperlink fixed on anaconda.org! (My guess is it would not.)

**Comment by jakirkham** [comment]
If it doesn't, let's open an issue on this feedstock and we can go from there

**Pull request merged**
